# <font color="purple" >  1- Python Lists   </font>
# <font color="purple" > 2 - Numpy   </font>
# <font color="red" > 3 - Python List VS Numpy   </font>

----------------
 ## 1- Python Lists


### create an empty list

In [1]:
my_list = []

### Define a list


In [2]:
my_list = [ 10, 18, 54, 36, 99]

In [3]:
my_list

[10, 18, 54, 36, 99]

In [4]:
stuff_list = [ 36.5, "Hello", 18, True, [25, 92] , -16.8, False]

In [5]:
stuff_list

[36.5, 'Hello', 18, True, [25, 92], -16.8, False]

### Accessing list items

| index  |  0  |  1  |  2  |  3  |  4 |
| ------:|:---:|:---:|:---:|:---:|---:|
| value  | 10  | 18  | 54  | 36  | 99 |

In [6]:
my_list[1]

18

| index  |  -5  |  -4  |  -3  |  -2  |  -1 |
| ------:|:---:|:---:|:---:|:---:|---:|
| value  | 10  | 18  | 54  | 36  | 99 |

In [7]:
my_list[-1]

99

### a slice of the list

In [8]:
my_list[1:4]

[18, 54, 36]

In [9]:
my_list[2:]

[54, 36, 99]

In [10]:
my_list[:3]

[10, 18, 54]

In [11]:
my_list[-2:]

[36, 99]

### Adding items to a list
- append
- extend
- insert

In [12]:
my_list.append(88)

In [13]:
my_list

[10, 18, 54, 36, 99, 88]

In [14]:
my_list.extend([18,96])

In [15]:
my_list

[10, 18, 54, 36, 99, 88, 18, 96]

In [16]:
my_list.insert(1,30)

In [17]:
my_list

[10, 30, 18, 54, 36, 99, 88, 18, 96]

### Removing elements
 - Deleting
 - Removing


In [18]:
my_list.remove(88)
my_list

[10, 30, 18, 54, 36, 99, 18, 96]

In [19]:
del my_list[-2]
my_list

[10, 30, 18, 54, 36, 99, 96]

In [20]:
my_list.sort() 
my_list

[10, 18, 30, 36, 54, 96, 99]

In [21]:
my_list.sort(reverse=True) 
my_list

[99, 96, 54, 36, 30, 18, 10]

#  <font color='red'> 2 - NumPy </font>

## The NumPy library is the core library for scientific computing in Python

In [22]:
import numpy as np

## Creating Arrays

In [23]:
a = np.array([1,2,3]) # 1D array
a

array([1, 2, 3])

In [24]:
b = np.array([(1.5,2.5,3) , (4,5,6)] , dtype = float) # 2D array
b

array([[1.5, 2.5, 3. ],
       [4. , 5. , 6. ]])

In [25]:
c = np.array([[(1.5,2,.5),(4,5,7)],[(9,8,7),(6,2.9,9)]] , dtype = float) # 3D array
c

array([[[1.5, 2. , 0.5],
        [4. , 5. , 7. ]],

       [[9. , 8. , 7. ],
        [6. , 2.9, 9. ]]])

## Initial Placeholder

In [26]:
d = np.zeros((3,4))  # Create an array of zeros
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
e = np.ones((2,3,5), dtype= np.int16) #  Create an array of ones
e

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [28]:
f = np.arange(10,75,5) # Create an array of evenly spaced values (step value)
[i for i in f]

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70]

In [29]:
k = np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)
[i for i in e]

[array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=int16),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=int16)]

In [30]:
l = np.full((2,2) ,7) # Create a constant array
l

array([[7, 7],
       [7, 7]])

In [31]:
m = np.eye(3) # Create a 2X2 identity matrix
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
n = np.random.random((3,3))
n

array([[0.14804457, 0.18007165, 0.38729425],
       [0.78452687, 0.04048365, 0.85317672],
       [0.42923756, 0.3605972 , 0.17742013]])

In [33]:
np.empty((3,4)) #Create an empty array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
a.shape #Array dimensions

(3,)

In [35]:
len(a) # Length of array


3

In [36]:
b.ndim #Number of array dimensions

2

In [37]:
e.size # Number of array  elements

30

In [38]:
b.dtype #Data type of array elements

dtype('float64')

In [39]:
b.dtype.name # Name of dataType

'float64'

In [40]:
b.astype(int) #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
b

array([[1.5, 2.5, 3. ],
       [4. , 5. , 6. ]])

# Array Mathematics



In [42]:
a , b

(array([1, 2, 3]),
 array([[1.5, 2.5, 3. ],
        [4. , 5. , 6. ]]))

In [43]:
 p = a-b 
p

array([[-0.5, -0.5,  0. ],
       [-3. , -3. , -3. ]])

In [44]:
np.subtract(a,b)

array([[-0.5, -0.5,  0. ],
       [-3. , -3. , -3. ]])

In [45]:
b+a

array([[2.5, 4.5, 6. ],
       [5. , 7. , 9. ]])

In [46]:
np.add(b,a)

array([[2.5, 4.5, 6. ],
       [5. , 7. , 9. ]])

In [47]:
a/b

array([[0.66666667, 0.8       , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [48]:
np.divide(a,b)

array([[0.66666667, 0.8       , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [49]:
a*b

array([[ 1.5,  5. ,  9. ],
       [ 4. , 10. , 18. ]])

In [50]:
np.multiply(a,b)

array([[ 1.5,  5. ,  9. ],
       [ 4. , 10. , 18. ]])

In [51]:
np.exp(b)

array([[  4.48168907,  12.18249396,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [52]:
np.sqrt(b)

array([[1.22474487, 1.58113883, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [53]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [54]:
np.cos(b)

array([[ 0.0707372 , -0.80114362, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [55]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [56]:
a.dot(k) # Dot product

ValueError: shapes (3,) and (9,) not aligned: 3 (dim 0) != 9 (dim 0)

## Comparison

In [ ]:
a == b

In [ ]:
a < b

In [ ]:
np.array_equal(a,b)

# Aggregate Functions

 - Array-wise sum
 - Array-wise minimum value
 - Maximum value of an array row
 - Cumulative sum of the elements
 - Mean
  - Median
 - Correlation coefficient
 - Standard deviation

In [ ]:
a.sum()

In [ ]:
a.min()

In [ ]:
b.max(axis = 0) 

In [ ]:
b

In [ ]:
b.cumsum(axis = 1) # Cumulative sum of the elements

In [ ]:
a.mean()

In [ ]:
b

In [ ]:
np.median(b)

In [ ]:
np.corrcoef(b) # Correlation coefficient

In [ ]:
np.std(b)

# Subsetting, Slicing, Indexing

In [ ]:
a[2]

In [ ]:
b[1,2]

In [ ]:
a[0:2]

In [ ]:
b[0:2,1]

In [ ]:
b[:1]

In [ ]:
c


In [ ]:
c[1,...]

In [ ]:
c[:,1,:]

In [ ]:
c[c<4]

In [ ]:
b

In [ ]:
b[[1, 0, 1, 0],[0, 1, 2, 0]]

In [ ]:
b[[1, 0, 1, 0]][:,[0,1,2,0]]

# Array Manipulation
 - Transposing Array
 - Changing Array Shape
 - Adding/Removing Elements
 - Combining Arrays

In [ ]:
b.T

In [ ]:
b.ravel() # Flatten the array

In [ ]:
b.reshape(3,2)

In [ ]:
h = np.arange(4,20,1)
g = h.reshape(2,8)
g

In [ ]:
g.resize(4,4)
g

In [ ]:
np.append(h,g)

In [ ]:
np.insert(a,1,50)

In [ ]:
np.delete(a,[0])

In [ ]:
np.concatenate((a,f),axis=0)

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((e,f))

In [ ]:
np.hsplit(b,3)

In [ ]:
np.vsplit(b,2)

#  <font color="Blue" >3 - Python List VS Numpy </font>

# Memory consumption between Numpy array and lists

In [ ]:
import numpy as np
import sys

s = range(1000) 
print("total size of list in Bytes" , sys.getsizeof(s)*len(s))

d = np.arange(1000)

print("total size of numpy array  in Bytes" , d.size*d.itemsize)


#   Time comparison between Numpy array and Python lists

In [ ]:
import time

In [ ]:
size = 1000000

list1 = range(size)
list2 = range(size)

array1 = np.arange(size)
array2 = np.arange(size)

initial_Time = time.time()
result_list = [ a*b for a,b in zip(list1 , list2)]

print("time of lists multiply" , time.time()-initial_Time)

initial_Time = time.time()
result_array = array1*array2

print("time of array multiply" , time.time()-initial_Time)


# <font color="orange" >Conclusion </font>
 ## <font color="Blue" >advantages of using numpy </font>
 ## - consumes less memory
 ## - Faster
 ## - Convenient to use
